### ISSUE TITLE
List of projects

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5581]
Here is a list of larger projects that could be done in pandoc.  For smaller projects, see [good first issues](https://github.com/jgm/pandoc/labels/good%20first%20issue).

- [ ] Modify readers and writers to handle the new table features (col/rowspan etc). (See #1024) (For individual readers and writers see #6311, ~~#6312~~, #6313, #6314, #6315, #6316, #6991, #6992)

- [ ]  Improve handling of figures with a new Block-level element.   (See #3177)
   
- [ ]  Explore allowing attributes on all elements.  (#684)

- [ ]  Create a flexible system for labeling objects (images, tables, code) and referring back by number and/or link. Or, more minimally:  handle `\label` and `\ref` better when parsing LaTeX.  (See #813, #165)

- [ ]  Automatic identifiers for images and tables in HTML output. (#208)  Must take care not to break existing documents relying on automatic identifiers for headers. (See also #1806.)

- [ ]  Syntax and (block or inline?) element for anchors (see #1299, #1621, also http://talk.commonmark.org/t/turning-empty-link-definitions-into-anchors/893).

- [ ]  Add a ConTeXt reader (#1423) -- should be possible to modify the LaTeX reader.

- [ ]  Add a plain TeX writer (#1541).

- [ ]  Make Format an enumerated type (#547).

**Comment by ozobi** [comment]
It would be great to have number 5 standardized. There are several workarounds out there making things complicated.

**Comment by link2xt** [comment]
Maybe pin this issue?

**Comment by xerus2000** [comment]
Instead of creating numbers and striking them through, you can use a checklist ;)

    - [ ] some project

- [ ] some project

**Comment by tarleb** [comment]
I'm sure John appreciates your help; I'm just worried that explaining a Markdown feature to the man who wrote most of GitHub's Markdown rendering engine might be a particularly inefficient use of your time :wink:

**Comment by link2xt** [comment]
There is now a "projects" tab where issues can be organized. They are moved automatically from "todo" to "done" as they are closed by default.

**Comment by jgm** [comment]
Closing this in favor of Projects tab.

**Comment by tarleb** [comment]
I guess it makes no sense then to keep this as a pinned issue, so I'm unpinning it. Do we want to pin a different one?
